#!/bin/sh

# Populate database if not exists
test -f /data/htdocs/db/tm.sqlite || cp /data/htdocs/db_schema/tm.sqlite /data/htdocs/db/tm.sqlite

# Configure system
# Set PHP timezone
sed -i "s#PHP_TIMEZONE#${PHP_TIMEZONE}#" /etc/php7/php.ini
sed -i "s#PHP_TIMEZONE#${PHP_TIMEZONE}#" /etc/php7/cli/php.ini

# Set PHP memory limit
sed -i "s#PHP_MEMORY_LIMIT#${PHP_MEMORY_LIMIT}#" /etc/php7/php.ini
sed -i "s#PHP_MEMORY_LIMIT#${PHP_MEMORY_LIMIT}#" /etc/php7/cli/php.ini

# Set cront timeuot for engine.php
sed -i "s#CRON_TIMEOUT#${CRON_TIMEOUT}#" /var/spool/cron/crontabs/root

# Set owner for app directory
chown -R nginx:nginx /data/htdocs

# Write temp files by nginx
chmod 777 /tmp

#check http-knocking start script
if [ -f /scripts/httpknocking.sh ];
# copy and run http-knocking start script
then
cp /scripts/httpknocking.sh /httpknocking.sh
chmod u+x /httpknocking.sh
/httpknocking.sh
#messging if http-knocking start script hadn't finded
else
echo “No http-knockig script”
fi

# Start apps
crond
php-fpm7
nginx -g 'daemon off;'
