#!/bin/sh

# Populate database if not exists
test -f /data/htdocs/db/tm.sqlite || cp /data/htdocs/db_schema/tm.sqlite /data/htdocs/db/tm.sqlite

# Configure system
# Set PHP timezone
sed -i "s#PHP_TIMEZONE#${PHP_TIMEZONE}#" /etc/php7/php.ini
sed -i "s#PHP_TIMEZONE#${PHP_TIMEZONE}#" /etc/php7/cli/php.ini

# Set PHP memory limit
sed -i "s#PHP_MEMORY_LIMIT#${PHP_MEMORY_LIMIT}#" /etc/php7/php.ini
sed -i "s#PHP_MEMORY_LIMIT#${PHP_MEMORY_LIMIT}#" /etc/php7/cli/php.ini

# Set cront timeuot for engine.php
sed -i "s#CRON_TIMEOUT#${CRON_TIMEOUT}#" /var/spool/cron/crontabs/root

# Set owner for app directory
chown -R nginx:nginx /data/htdocs

# Write temp files by nginx
chmod 777 /tmp

#check http-knocking start script
if [ -f /scripts/httpknocking.sh ];
# copy and run http-knocking start script
then
npm install -g http-knocking
cp /scripts/httpknocking.sh /httpknocking.sh
chmod u+x /httpknocking.sh
/httpknocking.sh
#messging if http-knocking start script hadn't finded
else
echo -e "No http-knockig script.Rerun container with expose only port 80 for direct access to TorMon webui!"
fi

#check rclone start script
if [ -f /scripts/rclonesync.sh ];
# copy and run rclone start script
then
cp /scripts/rclonesync.sh /rclonesync.sh
chmod u+x /rclonesync.sh
#messging if rclone start script hadn't finded
else
head -n -1 /var/spool/cron/crontabs/root > /var/spool/cron/crontabs/root.tmp ; mv /var/spool/cron/crontabs/root.tmp /var/spool/cron/crontabs/root
echo -e “No rclone script. rclone remove from cron.”
fi

# Start apps
crond
php-fpm7
nginx -g 'daemon off;'

tail -f /dev/null
